version: 2
jobs:
  deploy-cntk-language-understanding:
    docker:
      - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
      SERVICE_NAME: cntk-language-understanding
      SERVICE_RUN_SCRIPT: run_slot_tagging_service.py
      SERVICE_TEST_SCRIPT: test_slot_tagging_service.py
      SNETD_PORT: 7075
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
              nvidia-docker stop $DOCKER_CONTAINER_NAME_CNTK_LU || true && nvidia-docker rename $DOCKER_CONTAINER_NAME_CNTK_LU ${DOCKER_CONTAINER_NAME_CNTK_LU}_old || true
              nvidia-docker build \
                -t $DOCKER_IMAGE_NAME_CNTK_LU https://github.com/arturgontijo/cntk-language-understanding.git#master:/nlp-services/$SERVICE_NAME
              nvidia-docker run --runtime=nvidia \
                --name $DOCKER_CONTAINER_NAME_CNTK_LU \
                --restart unless-stopped \
                -p $SNETD_PORT:$SNETD_PORT \
                -v /home/admin/storage/LanguageUnderstanding/CNTK/Output:/opt/singnet/output \
                -di $DOCKER_IMAGE_NAME_CNTK_LU bash -c "source '/cntk/activate-cntk';git pull;python3 $SERVICE_RUN_SCRIPT"
            EOF
      - run:
          name: Remove Old Docker Container
          command: |
            ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
              nvidia-docker stop ${DOCKER_CONTAINER_NAME_CNTK_LU}_old || true && nvidia-docker rm ${DOCKER_CONTAINER_NAME_CNTK_LU}_old || true
            EOF
      - run:
          name: Test local
          command: |
            ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
              nvidia-docker exec -i $DOCKER_CONTAINER_NAME_CNTK_LU bash -c "source '/cntk/activate-cntk';python3 $SERVICE_TEST_SCRIPT auto"
            EOF
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-cntk-language-understanding